Models/ErrorViewModel.cs
using System;

namespace MoviesListed.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Lists.cs
using System.ComponentModel.DataAnnotations;

namespace MoviesListed.Models
{
    public class Lists
    {
        [Required(ErrorMessage = "Please select a class standing")]
        public string ListsID { get; set; }
        public string mTitle { get; set; }
    }
}

Models/movie.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace MoviesListed.Models
{
    public class Movie
    {

        // EF will instruct the database to automatically generate this value
        public int MovieId { get; set; }

        [Required(ErrorMessage = "Please enter a movie Name.")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Please enter a year .")]

        public int? Year { get; set; }

        [Required(ErrorMessage = "Please enter a Rating.")]

        public double Rating { get; set; }

        [Required(ErrorMessage = "Please enter a Description.")]

        public string Description { get; set; }

        [Required(ErrorMessage = "Please enter Actors/Actresses.")]

        public string Actors { get; set; }



        [Required(ErrorMessage = "Please enter a Runtime.")]

        public double? Runtime { get; set; }


        [Required(ErrorMessage = "Please select a Genre.")]

        public string ListsID { get; set; }

        public Lists Lists { get; set; }

        public string Slug =>
            Title?.Replace(' ', '-').ToLower() + '-' + Year?.ToString();
    }
}

Models/movieContext.cs
using Microsoft.EntityFrameworkCore;

namespace MoviesListed.Models
{
    public class movieContext : DbContext
    {

        public movieContext(DbContextOptions<movieContext> options)
            : base(options)
        { }

        public DbSet<Movie> Movie { get; set; }
        public DbSet<Lists> Lists { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Movie>().HasData(

                new Movie
                {
                    MovieId = 1,
                    Title = " The Shawshank Redemption",
                    Rating = 9.2,
                    Year = 1994,
                    ListsID = "D",
                    Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                    Runtime = 3.22,
                    Actors = "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler, Clancy Brown, etc"

                },
                new Movie
                {
                    MovieId = 5,
                    Title = "Saving Private Ryan",
                    Rating = 8.6,
                    Year = 1998,
                    ListsID = "D",
                    Description = "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
                    Runtime = 2.49,
                    Actors = "Tom Hanks, Tom Sizemore, Edward Burns, Barry Pepper, Adam Goldberg, etc"

                },
                    new Movie
                    {
                        MovieId = 4,
                        Title = "To Kill a Mockingbird",
                        Rating = 8.2,
                        Year = 1962,
                        ListsID = "D",
                        Description = "Atticus Finch, a lawyer in the Depression-era South, defends a black man against an undeserved rape charge, and his children against prejudice.",
                        Runtime = 2.09,
                        Actors = "Gregory Peck, John Megna, Frank Overton, Rosemary Murphy, Ruth White, etc"

                    },
                new Movie
                {
                    MovieId = 2,
                    Title = "Toy Story 4",
                    Rating = 4.5,
                    Year = 2019,
                    ListsID = "C",
                    Description = "Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woody's slight detour leads him to his long-lost friend Bo Peep. As Woody and Bo discuss the old days, they soon start to realize that they're worlds apart when it comes to what they want from life as a toy.",
                    Runtime = 1.40,
                    Actors = "Tom Hanks, Tim Allen, Annie Potts, Tony Hale, Keegan-Michael Key, etc"
                },
                new Movie
                {
                    MovieId = 3,
                    Title = "The Lord of the Rings: The Two Towers",
                    Rating = 13,
                    Year = 2002,
                    ListsID = "A",
                    Description = "Frodo and Sam (Sean Astin) discover they are being followed by the mysterious Gollum. Aragorn (Viggo Mortensen), the Elf archer Legolas and Gimli the Dwarf encounter the besieged Rohan kingdom, whose once great King Theoden has fallen under Saruman's deadly spell.",
                    Runtime = 3.43,
                    Actors = "Bruce Allpress, Sean Astin, John Bach, Sala Baker, Cate Blanchett, etc"

                }
            );

            modelBuilder.Entity<Lists>().HasData(

                      new Lists
                      {
                          ListsID = "A",
                          mTitle = "Action"

                      },
                      new Lists
                      {
                          ListsID = "C",
                          mTitle = "Crime"

                      },

                      new Lists
                      {
                          ListsID = "D",
                          mTitle = "Drama"

                      },

                      new Lists
                      {
                          ListsID = "H",
                          mTitle = "Horror"

                      },
                        new Lists
                        {
                            ListsID = "CO",
                            mTitle = "Comedy"

                        }

                      );

        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MoviesListed.Models;
using System.Linq;

namespace MoviesListed.Controllers
{
    public class HomeController : Controller
    {
        private movieContext context { get; set; }

        public HomeController(movieContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index()
        {
            var movies = context.Movie
                .Include(m => m.Lists)
                .OrderBy(m => m.Title)
                .ToList();
            return View(movies);
        }

        public IActionResult About()
        {
            ViewBag.Title = "contact";
            return View();
        }
    }
}

Controllers/movieController.cs
using Microsoft.AspNetCore.Mvc;
using MoviesListed.Models;
using System.Linq;

public class movieController : Controller
{
    private movieContext context { get; set; }

    public movieController(movieContext ctx)
    {
        context = ctx;
    }

    [HttpGet]
    public IActionResult Add()
    {
        ViewBag.Action = "Add";
        ViewBag.Lists = context.Lists.OrderBy(s => s.mTitle).ToList();
        return View("Edit", new Movie());
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        ViewBag.Action = "Edit";
        ViewBag.Lists = context.Lists.OrderBy(s => s.mTitle).ToList();
        var movie = context.Movie.Find(id);
        return View(movie);
    }

    [HttpPost]
    public IActionResult Edit(Movie movie)
    {
        if (ModelState.IsValid)
        {
            if (movie.MovieId == 0)
                context.Movie.Add(movie);
            else
                context.Movie.Update(movie);
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        else
        {
            ViewBag.Action = (movie.MovieId == 0) ? "Add" : "Edit";
            ViewBag.Lists = context.Lists.OrderBy(s => s.mTitle).ToList();
            return View(movie);
        }
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {
        var movie = context.Movie.Find(id);
        return View(movie);
    }

    [HttpPost]
    public IActionResult Delete(Movie movie)
    {
        context.Movie.Remove(movie);
        context.SaveChanges();
        return RedirectToAction("Index", "Home");
    }
}

Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "About";
}
<h1>Owner Ship</h1>
<p>
    Movie Information.
    La Salle University
    Philadelphia, PA  19141
</p>

Views/Home/Index.cshtml
@model List<Movie>
@{
    ViewBag.Title = "My Movies";
}

<h2>Movie Lists</h2>
<a asp-controller="movie" asp-action="Add">Add a new Movie</a>
<table class="table table-bordered table-striped">
    <thead>
        <tr><th>Title</th><th>Year</th><th>Rating</th><th>Description</th><th>Runtime</th><th>Actors</th><th>Genres</th><th></th></tr>
    </thead>
    <tbody>
        @foreach (var movie in Model)
        {
        <tr>
            <td>@movie.Title</td>
            <td>@movie.Year</td>
            <td>@movie.Rating</td>
            <td>@movie.Description</td>
            <td>@movie.Runtime</td>
            <td>@movie.Actors</td>
            <td>@movie.ListsID</td>
            <td>
                <a asp-controller="movie" asp-action="Edit"
                   asp-route-id="@movie.MovieId"
                   asp-route-slug="@movie.Slug">Edit</a>
                <a asp-controller="movie" asp-action="Delete"
                   asp-route-id="@movie.MovieId"
                   asp-route-slug="@movie.Slug">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.CSS" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="nav nav-pills">
        <a class="nav-items nav-link active" href="/">Home</a>

        <a class="nav-item nav-link" asp-controller="Home" asp-action="About">About</a>

        <nav />
    </div>

    <header class="jumbotron">
        <img id="logo" alt="The Movies"
             src="https://i.ytimg.com/vi/06RX7Wh-_48/maxresdefault.jpg"
             height="200" />
        <h1 class="col-sm-5">@ViewBag.Title</h1>



    </header>


    @RenderBody()




    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/movie/Delete.cshtml
@model Movie
@{
    ViewBag.Title = "Delete Movie";
}

<h2>Confirm Deletion</h2>
<h3>@Model.Title (@Model.Year @Model.Rating @Model.ListsID @Model.Description @Model.Runtime @Model.Actors  )</h3>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="MovieId" />

    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

Views/movie/Edit.cshtml
@model Movie
@{
    string title = ViewBag.Action + " movie";
    ViewBag.Title = title;
}

<h2>@title</h2>

<form asp-action="Edit" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Title">Name</label>
        <input asp-for="Title" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Year">Year</label>
        <input asp-for="Year" class="form-control">
    </div>




    <div class="form-group">
        <label asp-for="Rating">Rating</label>
        <input asp-for="Rating" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Runtime">Runtime</label>
        <input asp-for="Runtime" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Actors">Actors/Actresses</label>
        <input asp-for="Actors" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="ListsID">Genre</label>
        <select asp-for="ListsID" class="form-control">
            <option value="">Please select movie Genre</option>
            @foreach (Lists s in ViewBag.Lists)
            {
                <option value="@s.ListsID">
                    @s.mTitle
                </option>
            }
        </select>

    </div>



    <input type="hidden" asp-for="MovieId" />

    <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>